# Generated by Django 4.2.16 on 2024-11-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0002_rename_coins_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
