# Generated by Django 4.2.16 on 2024-11-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0003_coin_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='circulating_supply',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
