# Generated by Django 4.2.16 on 2024-11-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0004_alter_coin_circulating_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
