# Generated by Django 4.2.16 on 2024-11-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0005_alter_coin_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
