# Generated by Django 4.2.16 on 2024-11-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0006_alter_coin_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='circulating_supply',
            field=models.CharField(blank=True, null=True),
        ),
    ]
