# Generated by Django 4.2.16 on 2024-12-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0008_coin_price_alter_coin_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='fdv',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
    ]
