# Generated by Django 4.2.16 on 2025-01-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0009_coin_fdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='contract_address',
            field=models.CharField(blank=True, null=True),
        ),
    ]
