# Generated by Django 4.2.16 on 2025-01-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0010_coin_contract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='network',
            field=models.CharField(blank=True, null=True),
        ),
    ]
