# Generated by Django 4.2.16 on 2025-02-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0012_user_coin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Coin',
        ),
    ]
