# Generated by Django 4.2.16 on 2025-02-26 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0014_holderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='holderdata',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
