# Generated by Django 4.2.16 on 2025-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0015_holderdata_last_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='crypto_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=255),
        ),
    ]
