# Generated by Django 4.2.16 on 2025-03-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0016_alter_coin_crypto_id_alter_coin_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HolderData',
        ),
    ]
